import { ArrowRight, Check, ClipboardList, CalendarDays, MessageCircle, MapPin, Phone, Mail, ExternalLink, BookOpen } from 'lucide-react';
import { PageHero } from '../components/Layout';
import { Portrait } from '../components/Brand';
import { CTA, Notice, ServiceCard } from '../components/UI';
import { practice, serviceCategories, faqs } from '../config/practice';

export function Provider(){return <><PageHero eyebrow="Founder · CEO · Family Nurse Practitioner" title="A provider you can know. A practice built with purpose.">Prickly Pear Care puts the relationship between patient and provider at the center of every experience.</PageHero><section className="section provider-profile"><div className="shell"><header className="provider-profile__header"><span className="eyebrow">Meet Jennifer</span><h2>{practice.provider.name}</h2><p className="credential">{practice.provider.credentials}</p></header><div className="provider-profile__content"><div className="provider-profile__visual"><Portrait/><blockquote className="provider-profile__quote">“My goal is to create the kind of care experience where you feel comfortable asking questions, supported in your choices, and confident in what comes next.”</blockquote></div><div className="provider-bio provider-bio--side">{practice.provider.bio.map((paragraph,i)=><p className={i===0?'provider-bio__lead':''} key={paragraph}>{paragraph}</p>)}</div></div></div></section><CTA title="Let’s begin with a conversation."/></>}

export function About(){return <><PageHero eyebrow="About the practice" title="Rooted in care. Made for real life.">Prickly Pear Care is an independent, founder-led practice taking shape in Southern Arizona.</PageHero><section className="section"><div className="shell split"><div><span className="eyebrow">Why the prickly pear?</span><h2>Resilient, local, and full of life.</h2></div><div><p className="large-copy">The prickly pear thrives in the desert by adapting, growing, and making the most of its environment. It’s a fitting symbol for care that meets people where they are and helps them flourish.</p><p>The practice model is still being finalized. The foundation is already clear: time to talk, honest communication, and care guided by Jennifer’s experience.</p></div></div></section><section className="section section--olive"><div className="shell"><div className="section-heading"><div><span className="eyebrow">What guides us</span><h2>Simple values. Meaningful care.</h2></div></div><div className="three-col"><article><span>01</span><h3>Listen first</h3><p>Good decisions start with understanding your story, priorities, and questions.</p></article><article><span>02</span><h3>Keep it clear</h3><p>You deserve understandable options and a plan that makes sense in real life.</p></article><article><span>03</span><h3>Grow together</h3><p>Care should evolve with your needs, from prevention through life’s changes.</p></article></div></div></section><CTA title="There’s more to come." href="#/contact" action="Stay in the Loop">Follow the practice as launch plans, services, and patient information are confirmed.</CTA></>}

export function Services(){return <><PageHero eyebrow="Care & services" title="Care designed to meet you where you are.">Prickly Pear Care will combine insurance-based visits with cash-pay programs for weight management and hormone therapy.</PageHero><section className="section section--cream"><div className="shell"><Notice>{practice.availabilityNote} Contact us to confirm current availability.</Notice><div className="card-grid cards-spaced">{serviceCategories.map(x=><ServiceCard key={x.title} item={x}/>)}</div><div className="decision-panel"><div><span className="eyebrow">Before you book</span><h2>Clear information from the start.</h2></div><ul><li><Check/>Whether the visit uses insurance or cash pay</li><li><Check/>What the visit includes</li><li><Check/>Any eligibility or preparation requirements</li><li><Check/>Pricing or coverage details before confirmation</li></ul></div></div></section><CTA title="Not sure where to start?" href="#/contact" action="Ask a Question">Send a general question and our team can help point you in the right direction.</CTA></>}

export function NewPatients(){const steps=[[ClipboardList,'Tell us what you need','Choose a visit type or send an appointment request.'],[CalendarDays,'Find the right time','Share the date and time window that work best for you.'],[MessageCircle,'Get confirmation','The practice confirms details, forms, cost, and what to expect.']];return <><PageHero eyebrow="New patients" title="A clear, welcoming start.">Everything you need to feel prepared, with clear forms and next steps.</PageHero><section className="section"><div className="shell"><div className="steps">{steps.map(([Icon,t,d],i)=><article key={t}><span className="step-num">0{i+1}</span><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div><div className="prep-grid"><div><span className="eyebrow">Before your first visit</span><h2>What to have ready.</h2><p>We will share accepted plans, visit fees, required forms, policies, and arrival guidance as the opening date approaches.</p></div><ul className="check-list"><li><Check/>Photo ID and insurance card, if applicable</li><li><Check/>Medication and supplement list</li><li><Check/>Relevant records or recent test results</li><li><Check/>Your questions and goals for the visit</li></ul></div><Notice>Do not submit medical histories, symptoms, or sensitive health information through the general contact form.</Notice></div></section><CTA title="Ready to request a visit?"/></>}

export function Resources(){return <><PageHero eyebrow="Resources" title="Useful guidance from your care team.">A future home for practice news, patient education, forms, and trusted community resources.</PageHero><section className="section section--cream"><div className="shell resource-grid">{['Preparing for your first visit','Understanding your care options','Prickly Pear Care launch updates'].map((x,i)=><article className="resource-card" key={x}><div><BookOpen/><span>{i===2?'Practice news':'Patient guide'}</span></div><h3>{x}</h3><p>Content coming soon. Final resources will be clinically reviewed before publication.</p><span className="disabled-link">Coming soon</span></article>)}</div></section><CTA title="Have a resource question?" href="#/contact" action="Contact Us"/></>}

export function FAQ(){return <><PageHero eyebrow="Frequently asked questions" title="Questions are always welcome.">Here’s what we can share while Prickly Pear Care’s launch details are being finalized.</PageHero><section className="section"><div className="shell narrow faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section><CTA title="Still wondering about something?" href="#/contact" action="Ask Us"/></>}

export function Contact(){return <><PageHero eyebrow="Contact" title="We’d love to hear from you.">Ask a general question, join the launch list, or find the best way to connect.</PageHero><section className="section"><div className="shell contact-grid"><div><h2>Reach Prickly Pear Care</h2><div className="contact-items"><div><Phone/><span><small>Phone</small>{practice.phone}</span></div><a href={`mailto:${practice.email}`}><Mail/><span><small>Email</small>{practice.email}</span></a><div><MapPin/><span><small>Practice location</small>{practice.address}</span></div></div><Notice>For emergencies, call 911. This website and inbox are not monitored for urgent medical needs.</Notice></div><ContactForm/></div></section></>}

function ContactForm(){function prepareEmail(e){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const name=`${data.get('firstName')} ${data.get('lastName')}`;const body=[`Name: ${name}`,`Email: ${data.get('email')}`,`Phone: ${data.get('phone')||'Not provided'}`,`Topic: ${data.get('topic')}`,'',data.get('message')].join('\n');window.location.assign(`mailto:${practice.email}?subject=${encodeURIComponent(`Website message from ${name}`)}&body=${encodeURIComponent(body)}`);form.querySelector('.form-success').hidden=false}return <form className="form" onSubmit={prepareEmail}><h2>Send a general message</h2><div className="field-row"><label>First name<input required name="firstName" autoComplete="given-name"/></label><label>Last name<input required name="lastName" autoComplete="family-name"/></label></div><label>Email<input required type="email" name="email" autoComplete="email"/></label><label>Phone (optional)<input type="tel" name="phone" autoComplete="tel"/></label><label>What can we help with?<select name="topic"><option>Practice updates</option><option>General care question</option><option>Becoming a patient</option><option>Other</option></select></label><label>Message <small>Do not include medical or sensitive information.</small><textarea name="message" rows="5" required/></label><button className="button" type="submit">Prepare Email <ArrowRight size={17}/></button><p className="form-success" hidden>Your email app should open with a prepared message. Review it, then press Send.</p></form>}

export function Portal(){return <><PageHero eyebrow="Patient portal" title="Your care, in one secure place.">The portal will connect to the practice’s chosen health record system when available.</PageHero><section className="section"><div className="shell narrow centered"><div className="portal-icon"><ExternalLink/></div><h2>Portal access is coming soon.</h2><p className="large-copy">Once connected, patients will be able to use the official portal for secure messages, forms, results, records, and other supported features.</p><Notice>Never send private health information through general email or website contact forms.</Notice><div className="button-row centered-row"><a className="button" href="#/contact">Contact the Practice</a><a className="button button--ghost" href="#/faq">View FAQ</a></div></div></section></>}

export function Legal({type}){const privacy=type==='privacy';return <><PageHero eyebrow="Legal" title={privacy?'Privacy notice':'Terms & accessibility'}>{privacy?'How website information is handled.':'Important information about using this website.'}</PageHero><section className="section"><div className="shell narrow prose"><p><strong>Draft for legal review · Last updated August 2026</strong></p>{privacy?<><h2>Website privacy</h2><p>This website is designed to collect only the information needed to respond to general inquiries and appointment requests. Production forms must be connected to an approved, secure service before launch.</p><h2>Waitlist information</h2><p>When the secure waitlist is enabled, the practice may collect contact information, ZIP code, care-format preference, preferred timeframe, consent status, and submission metadata through its approved form provider. This information is used for launch planning and related communications. Joining the waitlist does not create a provider-patient relationship or guarantee care.</p><h2>Health information</h2><p>Do not submit diagnoses, symptoms, medical histories, or other sensitive health information through general website forms. A future patient portal or approved clinical workflow should be used for protected health information.</p><h2>Analytics and cookies</h2><p>Any analytics or cookies added before launch should be documented here, configured to avoid collecting health information, and reviewed for applicable privacy requirements.</p></>:<><h2>Informational use</h2><p>This site provides general information and does not create a provider–patient relationship or replace professional medical advice.</p><h2>Emergencies</h2><p>This website is not monitored for emergencies. Call 911 or seek immediate emergency care when needed.</p><h2>Accessibility</h2><p>Prickly Pear Care aims to provide an inclusive digital experience. If you encounter a barrier, contact the practice so an alternative can be provided.</p></>}<Notice>These are launch-ready structural drafts, not legal advice. Counsel and the final privacy/security vendors should review them before publication.</Notice></div></section></>}
