import { ArrowRight, HeartHandshake, ShieldCheck, Sprout } from 'lucide-react';
import { practice, serviceCategories } from '../config/practice';
import { Portrait } from '../components/Brand';
import { ServiceCard, CTA } from '../components/UI';

export default function Home(){return <>
  <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow">Relationship-centered care · Southern Arizona</span><h1>Care that <em>grows</em> with you.</h1><p className="lead">{practice.description}</p><div className="button-row"><a className="button" href="#/booking">Book a Visit <ArrowRight size={17}/></a><a className="button button--ghost" href="#/provider">Meet Your Provider</a></div><p className="location">{practice.serviceArea}</p></div><Portrait/></div><div className="desert-line"/></section>
  <section className="section intro"><div className="shell split"><div><span className="eyebrow">Care led by empathy</span><h2>Known, heard, and genuinely cared for.</h2></div><div><p className="large-copy">Healthcare should feel like a relationship—not a transaction. Jennifer approaches every person with kindness, listens without judgment, and pairs human connection with an unwavering devotion to safe, evidence-informed care excellence.</p><a className="arrow-link" href="#/about">Why Prickly Pear Care <ArrowRight size={17}/></a></div></div></section>
  <section className="section section--cream"><div className="shell"><div className="section-heading"><div><span className="eyebrow">One practice · two ways to access care</span><h2>A hybrid model, made clearer.</h2></div><p>Prickly Pear Care will combine insurance-based care with focused cash-pay programs. Medical weight-loss care and hormone therapy will be cash pay.</p></div><div className="card-grid">{serviceCategories.map(x=><ServiceCard key={x.title} item={x}/>)}</div></div></section>
  <section className="section founder"><div className="shell founder-grid"><Portrait/><div><span className="eyebrow">Meet Jennifer</span><h2>Care begins with trust.</h2><p className="large-copy">Prickly Pear Care is founder-led, so the person shaping the practice is also the person listening to you. Jennifer brings warmth to difficult conversations, respects the person behind every concern, and holds every care decision to a high clinical standard.</p><div className="values"><div><HeartHandshake/><span><strong>Empathetic</strong>You are heard without judgment.</span></div><div><ShieldCheck/><span><strong>Excellent</strong>Care grounded in evidence and safety.</span></div><div><Sprout/><span><strong>Devoted</strong>A partner invested in your wellbeing.</span></div></div><a className="button button--ghost" href="#/provider">Get to know Jennifer</a></div></div></section>
  <CTA/>
</>}
