export const practice = {
  name: 'Prickly Pear Care',
  legalName: 'Prickly Pear Primary Care PLLC',
  tagline: 'Care that grows with you.',
  careModel: 'Patient-led care',
  description: 'Patient-led care built on careful listening, clear answers, kindness, and strong clinical standards.',
  serviceArea: 'Proudly serving Marana, Tucson, and surrounding communities.',
  dpcIndividualStartingPrice: 99,
  phone: 'Coming soon',
  phoneHref: '',
  email: 'jcarlile@pricklypearcareaz.com',
  address: 'Coming soon',
  hours: ['Monday–Thursday · 8:00 AM–5:00 PM', 'Friday · By appointment'],
  provider: {
    name: 'Jennifer Carlile',
    credentials: 'MSN, FNP-BC · Founder, CEO & Family Nurse Practitioner',
    bio: [
      'I’m Jennifer Carlile, FNP-BC, and I’ve been practicing as a Family Nurse Practitioner for over 13 years, with more than 9 years serving patients in the Marana and Northwest Tucson communities.',
      'Over the years, I’ve seen how difficult it can be to receive truly personalized care when you don’t have the opportunity to see the same provider who knows you and your story. I believe there is something incredibly valuable about having a provider who takes the time to listen, knows your history, and is invested in your health for the long term. That belief is what inspired me to create Prickly Pear Care.',
      'My favorite part of primary care is building lasting relationships with my patients and helping them navigate the healthcare system. My goal is for every patient to feel heard, valued, and confident in their care.',
      'Outside of the office, I’m happily married and a proud mom to my daughter. I enjoy reading, crafting, spending time outdoors and trying new foods.',
      'I’m excited to offer a more personal, accessible, patient-led approach to care for the community I’ve been proud to serve for so many years.',
    ],
    portrait: '/images/provider-portrait.png',
    npi: '1609217256',
    license: 'Arizona AP5088',
    community: 'International medical missions with Hope Without Borders',
  },
  availabilityNote: 'Prickly Pear Care plans to offer insurance-based primary care, Direct Primary Care membership, and select cash-pay services. DPC pricing and intended inclusions are now available to review. Final insurance participation, enrollment terms, cash-pay offerings, eligibility, and opening timing are still being finalized.',
};

export const serviceCategories = [
  {
    icon: 'heart',
    title: 'Insurance-Based Primary Care',
    description: 'Use health insurance for covered primary-care services, subject to plan participation, coverage, copays, deductible, and coinsurance.',
    status: 'Planned care pathway',
    href: '#/services',
  },
  {
    icon: 'sparkle',
    title: 'Direct Primary Care Membership',
    description: 'A predictable monthly membership designed around continuity, more personal access, and an ongoing relationship with Jennifer.',
    status: 'Relationship-focused option',
    href: '#/dpc',
  },
  {
    icon: 'flower',
    title: 'Select Cash-Pay Services',
    description: 'Specific services offered at transparent, upfront prices outside insurance coverage. The final service list and pricing are coming soon.',
    status: 'Planned care pathway',
    href: '#/services',
  },
];

export const faqs = [
  ['When will Prickly Pear Care open?', 'Launch timing is being finalized. Join the Waitlist to receive opening and enrollment updates.'],
  ['What is Direct Primary Care?', 'Direct Primary Care is a primary-care membership paid directly to the practice rather than billed to insurance for the primary-care services included in the membership. Membership pricing begins at $99 per month for an individual. Final eligibility, access, and enrollment terms will be published before enrollment opens.'],
  ['How much will DPC membership cost?', 'Individual DPC membership pricing begins at $99 per month. Household pricing and final membership terms are still being finalized and will be shown clearly before enrollment.'],
  ['Why would someone choose DPC?', 'DPC is designed to make primary care more predictable and less transactional. Instead of starting with another visit charge every time something comes up, members can begin with their ongoing primary-care relationship, subject to the final access and inclusion terms.'],
  ['Is DPC always cheaper?', 'Not for everyone. DPC can make primary-care costs more predictable and may reduce visit-by-visit out-of-pocket friction, but whether it lowers your total healthcare spending depends on how often you use care, what your insurance covers, and what is included in the final membership.'],
  ['Does DPC replace health insurance?', 'No. Direct Primary Care membership is separate from health insurance and is not health insurance. Many people maintain coverage for hospital care, specialists, imaging, medications, emergencies, and other services outside the DPC membership.'],
  ['Can my small business help pay for DPC for employees?', 'Prickly Pear Care is exploring employer-sponsored DPC arrangements for local small businesses. An employer may be able to contribute toward or sponsor a defined primary-care membership for eligible employees while employees continue to use major medical insurance for care outside the DPC membership. Final employer pricing, participation requirements, eligibility, tax or benefit treatment, and enrollment terms are still being developed and should be reviewed with the appropriate benefits and tax professionals.'],
  ['Will Prickly Pear Care still offer insurance-based care?', 'That is the plan. Prickly Pear Care intends to offer insurance-based primary care in addition to DPC membership. Final participating plans and billing details will be published before care begins.'],
  ['Will cash-pay care be available?', 'Select cash-pay services are planned so patients can access certain services at transparent prices without using insurance. The final service list and pricing are still being developed.'],
  ['What if I wake up sick or have a new concern?', 'DPC is intended to make it easier to start by contacting your primary-care practice. Jennifer can help determine whether the next step should be a message, a visit, testing, treatment, or another level of care. Final communication and response standards will be published before enrollment.'],
  ['Will every prescription question require another appointment?', 'Not necessarily. Some medication questions or follow-up needs may be handled without another separately billed office visit when that is clinically appropriate. Jennifer will still recommend a visit whenever an exam, monitoring, or additional evaluation is needed.'],
  ['Can Jennifer order imaging or refer me to a specialist?', 'Yes, primary-care clinicians can coordinate referrals and order appropriate testing when clinically indicated. Imaging, specialist care, and other outside services are generally separate from the DPC membership and may be billed by the outside facility or clinician.'],
  ['What is usually outside a DPC membership?', 'Hospital care, emergency care, specialist visits, advanced imaging, many medications, and services performed by outside organizations are typically separate from a primary-care membership. Prickly Pear Care will publish its exact inclusions and exclusions before enrollment.'],
  ['What happens after I join the waitlist?', 'The waitlist is not enrollment. You will receive opening updates and, when enrollment is ready, the exact monthly price, household options, included services, exclusions, access expectations, and any applicable HSA information before deciding whether to join. Clinical onboarding and scheduling happen after enrollment.'],
  ['Can I use an HSA to pay for DPC?', 'Federal HSA rules for qualifying Direct Primary Care arrangements changed in 2026. Prickly Pear Care will confirm whether its final membership structure qualifies before advertising HSA payment as available. Individual HSA eligibility can vary, so patients should verify their own benefits and tax situation.'],
  ['Will telehealth be available?', 'Telemedicine is intended to be included with DPC membership when clinically appropriate. Final availability, communication standards, technology, and licensing terms will be confirmed before enrollment.'],
  ['Can I book online?', 'Live patient scheduling is not open yet. The website is being built to support website-based booking and a future EHR scheduling connection once the practice is ready to open appointments.'],
  ['Is this form for urgent medical needs?', 'No. Do not use website forms for emergencies or urgent symptoms. Call 911 for an emergency.'],
];
